# Default configuration for xFlyPlot
world-prefix: xflyplot-
# Language for messages (en or pl)
language: pl
# Amount of placed blocks needed to gain an island level
level-blocks: 100
# Size of the visible world border around each island
island-border-size: 64
# Sound names can be changed
sounds:
  start: ENTITY_PLAYER_LEVELUP
  teleport: ENTITY_ENDERMAN_TELEPORT
  phase-complete: UI_TOAST_CHALLENGE_COMPLETE
  island-delete: ENTITY_WITHER_DEATH
  bonus: ENTITY_EXPERIENCE_ORB_PICKUP

# Points awarded for placing blocks. Material names follow Bukkit enum names.
# 'default' value is used when a material is not listed.
block-points:
  default: 1
  diamond_block: 5
  gold_block: 3
  iron_block: 2

upgrade:
  cost: 500
  increment: 16
