name: xFlyPlot
version: 1.0
main: com.AJgorEx.xFlyPlot.Main
api-version: 1.21
author: AJgorEx
description: Zaawansowany plugin OneBlock z własnym światem, bossbarem i fazami
commands:
  oneblock:
    description: Zarządza wyspą OneBlock
    usage: /oneblock [home|reload]
    aliases: [ob, startblock]
permissions:
  oneblock.use:
    description: Pozwala na używanie komendy /oneblock
    default: true
  oneblock.reload:
    description: Pozwala na przeładowanie faz
    default: op
